from typing import Any, overload

from django import forms as forms
from django.forms import MediaDefiningClass as MediaDefiningClass
from django.utils.functional import Promise as Promise, cached_property as cached_property

DICT_RESERVED_KEYS: list[str]
STRING_REF_MIN_LENGTH: int

class UnpackableTypeError(TypeError): ...

class Node:
    id: int | None
    seen: bool
    use_id: bool
    def __init__(self) -> None: ...
    def emit(self) -> Any: ...

class ValueNode(Node):
    value: Any
    def __init__(self, value: Any) -> None: ...
    def emit_verbose(self) -> dict[str, Any]: ...
    def emit_compact(self) -> Any: ...

class StringNode(Node):
    value: str
    def __init__(self, value: str) -> None: ...
    def emit_verbose(self) -> dict[str, str]: ...
    def emit_compact(self) -> str: ...

class ListNode(Node):
    value: list[Node]
    def __init__(self, value: list[Node]) -> None: ...
    def emit_verbose(self) -> dict[str, list[Any]]: ...
    def emit_compact(self) -> list[Any]: ...

class DictNode(Node):
    value: dict[str, Node]
    def __init__(self, value: dict[str, Node]) -> None: ...
    def emit_verbose(self) -> dict[str, dict[str, Any]]: ...
    def emit_compact(self) -> dict[str, Any]: ...

class ObjectNode(Node):
    constructor: str
    args: list[Node]
    def __init__(self, constructor: str, args: list[Node]) -> None: ...
    def emit_verbose(self) -> dict[str, Any]: ...
    def emit_compact(self) -> dict[str, Any]: ...

class BaseAdapter:
    def build_node(self, obj: Any, context: ValueContext) -> Node: ...

class StringAdapter(BaseAdapter):
    def build_node(self, obj: str, context: ValueContext) -> StringNode: ...

class DictAdapter(BaseAdapter):
    def build_node(self, obj: dict[Any, Any], context: ValueContext) -> DictNode: ...

class Adapter(BaseAdapter, metaclass=MediaDefiningClass):
    js_constructor: str
    @property
    def media(self) -> forms.Media: ...
    def js_args(self, obj: Any) -> list[Any]: ...
    def get_media(self, obj: Any) -> forms.Media: ...
    def pack(self, obj: Any, context: ValueContext) -> tuple[str, list[Any]]: ...
    def build_node(self, obj: Any, context: ValueContext) -> ObjectNode: ...

class AutoAdapter(Adapter):
    @property
    def media(self) -> forms.Media: ...
    def pack(self, obj: Any, context: ValueContext) -> tuple[str, list[Any]]: ...

class JSContextBase:
    media: forms.Media
    media_fragments: set[str]
    telepath_js_path: str
    registry: AdapterRegistry
    def __init__(self) -> None: ...
    @property
    def base_media(self) -> forms.Media: ...
    def add_media(
        self,
        media: forms.Media | None = ...,
        js: str | list[str] | None = ...,
        css: dict[str, list[str]] | None = ...,
    ) -> None: ...
    def pack(self, obj: Any) -> Any: ...

class AdapterRegistry:
    js_context_base_class: type[JSContextBase]
    telepath_js_path: str
    adapters: dict[type[Any], BaseAdapter]
    def __init__(self, telepath_js_path: str = ...) -> None: ...
    @overload
    def register(self, adapter: BaseAdapter, cls: type[Any]) -> None: ...
    @overload
    def register(self, cls: type[Any]) -> type[Any]: ...
    @overload
    def register(self, *, adapter: BaseAdapter | None = ...) -> Any: ...
    def find_adapter(self, cls: type[Any]) -> BaseAdapter | None: ...
    @cached_property
    def js_context_class(self) -> type[JSContextBase]: ...

class ValueContext:
    parent_context: JSContextBase
    registry: AdapterRegistry
    raw_values: dict[int, Any]
    nodes: dict[int, Node]
    next_id: int
    def __init__(self, parent_context: JSContextBase) -> None: ...
    def add_media(self, *args: Any, **kwargs: Any) -> None: ...
    def build_node(self, val: Any) -> Node: ...

registry: AdapterRegistry
JSContext: type[JSContextBase]
register = registry.register
